name: Deploy

on:
  push:
    branches:
      - main
<<<<<<< HEAD
      - prod
=======
>>>>>>> 96758a1 (Implement github action to deploy to test environment)

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Trigger deploy
        run: |
          curl -fsS -X POST ${{ secrets.HOOKURL }} -H "X-Key: ${{ secrets.HOOKSECRET }}"
